export const ADD_COMMENT = 'ADD_COMMENT';
export const LOCATIONS_LOADING = 'LOCATIONS_LOADING';
export const LOCATIONS_FAILED = 'LOCATIONS_FAILED';
export const ADD_LOCATIONS = 'ADD_LOCATIONS';
export const ADD_COMMENTS = 'ADD_COMMENTS';
export const COMMENTS_FAILED = 'COMMENTS_FAILED';
export const ADD_FEEDBACK = 'ADD_FEEDBACK';
